### PR TITLE
Add sensor config for Beelink EQ12/S12 series

### PR DESCRIPTION
**Pull request by graysky2**

### CODE REVIEW

**Comment by frankcrawford** [comment]
@graysky2 are you able to give more description of what a Beelink EQ12/S12 is, so others can work out if it is applicable to them.

**Comment by graysky2** [comment]
@frankcrawford - it's [this](https://minipcreviewer.com/beelink-mini-pc-eq12-review/) mini PC based on an Intel N100.

**Comment by frankcrawford** [comment]
@graysky2 any chance you could add some comments about that as comments to the top of the file?  It will make it easier for future users to know if it is appropriate for them.

**Comment by graysky2** [comment]
Sure, done.

**Pull request merged**
